chat_app/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('chat_app.views',
    url(r'^news/$', 'main'),
    url(r'^forum/', 'main'),
    url(r'^shop/', 'main'),
    url(r'^pedia/main/about/', 'main'),
    url(r'^pedia/main/rules/', 'main'),
    url(r'^$', 'main'),
    url(r'^show_tabs/', TemplateView.as_view(template_name='tabs.html')),
)

tornadochat/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('chat_app.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

chat_app/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from tornadochat.settings import MAX_ROOMS_COUNT


class CustomUser(models.Model):
    user = models.OneToOneField(User)
    room = models.ForeignKey('Room')
    something_special = models.CharField(max_length=150, blank=True)

    def __unicode__(self):
        return '[{}] {}'.format(self.user.username, self.something_special)


class Room(models.Model):
    title = models.TextField(unique=True)

    def __unicode__(self):
        return '{0}'.format(self.title)

    def save(self, force_insert=False, force_update=False, using=None):
        if self.pk == 1:
            raise NotAllowedToChange
        if Room.objects.count() >= MAX_ROOMS_COUNT:
            raise ReachMaxRoomCount
        super(Room, self).save(force_insert, force_update, using)

    def delete(self, using=None):
        if self.pk == 1:
            raise NotAllowedToDelete
        super(Room, self).delete(using)

    def natural_key(self):
        return self.title


class Message(models.Model):
    text = models.TextField()
    username = models.TextField()
    room = models.ForeignKey(Room)
    datetime = models.DateTimeField(auto_now_add=True, db_index=True)

    def __unicode__(self):
        return u'{0}'.format(self.text)


class NotAllowedToChange(Exception):
    """При попытке изменить запись основной комнаты"""
    pass


class NotAllowedToDelete(Exception):
    """При попытке удалить основную комнату"""
    pass


class ReachMaxRoomCount(Exception):
    """При создании комнат больше разрешенного количества"""
    pass

chat_app/forms.py
from django import forms
from .models import CustomUser


class SelectRooms(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('room',)

chat_app/views.py
#coding:utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import RequestContext
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import login_required
from .models import Room, CustomUser
from forms import SelectRooms


@login_required(login_url='/login')
def main(request):
    cust_user = get_object_or_404(CustomUser, user=request.user.id)
    room_title = cust_user.room.title
    form = SelectRooms(instance=cust_user)
    # form['room'].css_classes('form-control')
    is_forum_page = request.path.startswith('/forum')
    return render(request, 'main.html', {'room_title': room_title,
                                         'form':form,
                                         'is_forum_page': is_forum_page})

tornadochat/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
{#    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>#}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"/>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
{#    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css"/>#}
{#    <link rel="stylesheet" href="{{ STATIC_URL }}js/bootstrap.min.js"/>#}
<style type="text/css">
    body {background-color: #F5F5F5}

    #rooms_area div {
        border-style: solid none solid solid;
        border-width: 1px;
        background-color: rgb(97, 97, 97);
    }

    #rooms_area div.active_room {
        background-color: #F5F5F5;
    }

    .glyphicon-edit, .glyphicon-remove {
        cursor: pointer;
    }

</style>
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

tornadochat/templates/chat.html
<script>
var ws;

$(window).on('beforeunload', function() {
    var current_room_name = $('.active_room').text()
    mess = {'msg_from': 'chat',
            'msg': {'room': current_room_name,
                    'type': 'disconnect'}};
    ws.send(JSON.stringify(mess));
})

function get_time() {
    var currentTime = new Date()
    hours = currentTime.getHours()
    minutes = currentTime.getMinutes()
    now_time = '<strong>[' + hours + ":" + minutes + '] </strong>'
    return now_time
};

function send_message(event) {
    var message = $('input#txt_message')

    function send() {
        if (message.val().trim() == '') {
            alert('You cant send empty message')
        }
        else {
            var current_room_name = $('.active_room').text()
            var json = mess = {'msg_from': 'chat',
                               'msg': {'type': 'text',
                                       'room': current_room_name,
                                       'text': message.val()}};
            ws.send(JSON.stringify(json));
            message.val('');
        }};

    if (event.type == 'keypress') {
        if (event.which == 13 || event.keyCode == 13) {
            send();
            return false;}
        return true;
    }
    else {
        send();
    }
}

function change_room(elem) {
    var curr_room = $('#rooms_area div').filter('.active_room')
    var current_room_name = curr_room.text()
    var new_room = $(elem).parent();
    var new_room_name = new_room.text();

    mess = {'msg_from': 'chat',
            'msg': {'room': current_room_name,
                    'new_room': new_room_name,
                    'type': 'change_room'}};
    ws.send(JSON.stringify(mess));

    curr_room.removeClass('active_room');
    $('#chat_area div').hide()
    new_room.addClass('active_room');
    $('#chat_area div').filter('#'+new_room_name).show();
}

function create_room(elem) {
    while (true) {
        var created_room = prompt('Введите название комнаты')
        if (created_room.trim() == '') { // тут может быть undefined, надо проверять.
            alert('Имя комнаты не должно быть пустым');
            continue;}
        break;
    }
    mess = {'msg_from': 'chat',
            'msg': {'type': 'create_room',
                    'created_room': created_room}};
    ws.send(JSON.stringify(mess));
}

function edit_room_name(elem) {
    var room_name = $(elem).parent().text();
    while (true) {
        var edited_name = prompt('Измените название комнаты');
        if (edited_name.trim() == '') { // тут может быть undefined, надо проверять.
            alert('Имя комнаты не должно быть пустым');
            continue;}
        break;
    }
    mess = {'msg_from': 'chat',
            'msg': {'type': 'edit_room_name',
                    'room': room_name,
                    'edited_name': edited_name}};
    ws.send(JSON.stringify(mess));
}

function delete_room(elem) {
    var deleted_name = $(elem).parent().text();
    var delete_room = confirm('Удалить комнату?');
    if (delete_room) {
        mess = {'msg_from': 'chat',
            'msg': {'type': 'delete_room',
                    'deleted_room': deleted_name}};
        ws.send(JSON.stringify(mess));
    };
}

$(function() {
    ws = new WebSocket("ws://{{ tornado_full_address }}/websocket");
    ws.onmessage = function(event){
        var d = JSON.parse(event.data);
        var room_html = $('<div class="row">' +
                          '<a onclick="change_room(this)"></a>' +
                          {% if perms.chat_app.delete_room %}
                              '<span class="glyphicon glyphicon-remove text-danger pull-right" onclick="delete_room(this)"></span>' +
                          {% endif %}
                          {% if perms.chat_app.change_room %}
                              '<span class="glyphicon glyphicon-edit text-success pull-right" onclick="edit_room_name(this)"></span>' +
                          {% endif %}
                          '</div>')
        if ('initialization' == d['type']) {
            for (var i=0;i<d['rooms'].length;i++) {
                var room = d['rooms'][i];
                $('a', room_html).attr('href', '#'+room)
                $('a', room_html).text(room)
                $('#rooms_area').append(room_html.wrap('<div>').parent().html());
                $('#chat_area').append('<div id="'+room+'"></div>');
            };
            var main_room = $('#rooms_area div').first();
            $('#chat_area div').hide();
            main_room.addClass('active_room');
            $('#chat_area div').filter('#'+main_room.text()).show()
        }
        else if('text' == d['type']) {
            var mess = get_time() + d['user'] + ':' + d['text'] + '<br>';
            var required_chat_div = '#chat_area #' + d['room'];
            $(required_chat_div).append(mess);
        }
        else if ('all_users' == d['type']) {
            $('#users_area').empty();
            for (var i=0;i<d['users'].length;i++) {
                var user = d['users'][i];
                $('#users_area').append('<div id="'+user+'">'+user+'</div>');
            };
        }
        else if ('add_user' == d['type']) {
            $('#users_area').append('<div id="'+d['user']+'">'+d['user']+'</div>').scrollTop($('#users_area').innerHeight());
            var mess = get_time() + 'Пользователь ' + d['user'] + ' вошел в комнату <br>';
            var required_chat_div = '#chat_area #' + d['room'];
            $(required_chat_div).append(mess);
        }
        else if ('messages_history' == d['type']) {
            var data = JSON.parse(d['data']);
            for (var i=0;i<data.length;i++) {
                var mess = get_time() + data[i]['fields']['username'] + ':' + data[i]['fields']['text'] + '<br>';
                var required_chat_div = '#chat_area #' + data[i]['fields']['room'];
                $(required_chat_div).append(mess);
            }
        }
        else if ('remove_user' == d['type']) {
            $('#users_area div').remove('#'+d['user']);
            var mess = get_time() + 'Пользователь ' + d['user'] + ' покинул комнату <br>';
            var required_chat_div = '#chat_area #' + d['room'];
            $(required_chat_div).append(mess);
        }
        else if ('create_room' == d['type']) {
            var created_room = d['created_room'];
            $('a', room_html).attr('href', '#'+created_room);
            $('a', room_html).text(created_room);
            $('#rooms_area').append(room_html.wrap('<div>').parent().html());
            $('#chat_area').append('<div id="'+created_room+'"></div>');
        }
        else if ('edit_room_name' == d['type']) {
            $('#rooms_area div a:contains("'+d['room']+'")').text(d['edited_name']);
        }
        else if ('delete_room' == d['type']) {
            $('#rooms_area div').remove(':contains("'+d['deleted_room']+'")');
            $('#chat_area div').remove('#'+d['deleted_room']);
        }
{#        else if ('drop_to_main' == d['type']) {#}
{#            var curr_room = $('#rooms_area div').filter('.active_room')#}
{#            var current_room_name = curr_room.text()#}
{#            var new_room = $(elem).parent();#}
{#            var new_room_name = new_room.text();#}
{#        #}
{#            curr_room.removeClass('active_room');#}
{#            $('#chat_area div').hide()#}
{#            new_room.addClass('active_room');#}
{#            $('#chat_area div').filter('#'+new_room_name).show();#}
{#            #}
{#            $('#users_area').empty();#}
{#            for (var i=0;i<d['users'].length;i++) {#}
{#                var user = d['users'][i];#}
{#                $('#users_area').append('<div id="'+user+'">'+user+'</div>');#}
{#            };#}
{#        }#}
        else if('disconnect' == d['type']) {
            var remove_nick = d['user'];
            $('#'+remove_nick).remove();
        }
        else if ('error' == d['type']) {
            alert(d['text']);
        }
        else if ('already_exist' == d['type']) {
            $('#whole_chat>div').text(d['text']);
        }
    }

    $('#expand').on('click', function() { $('#whole_chat').slideToggle('slow'); });
    $('#txt_message').on('keypress', {}, send_message);
    $('#submit').on('click', send_message);
    {% if perms.chat_app.add_room %}
        $('#create').on('click', create_room);
    {% endif %}

});

</script>

<div class="row" id="container">
<div class="col-md-offset-2 col-md-8">

    <div class="row" style="background-color: rgb(133,133,133)">
    <div class="col-md-1">
        <a id="expand" href="#" style="color: #E76600"><strong>ЧАТ</strong></a>
    </div>
    </div>

    <div class="row" id="whole_chat" style="border-style:solid;border-width:1px;">
    <div class="col-md-12">

        <div class="row">
            <div class="col-md-2" id="rooms_area" style="border-bottom-style: solid;border-width:1px;height:350px;overflow:auto;">
            </div>
            <div class="col-md-8" id="chat_area" style="border-style: none solid solid;border-width:1px;height:350px;overflow:auto;"></div>
            <div class="col-md-2" id="users_area" style="border-bottom-style: solid;border-width:1px;height:350px;overflow:auto;"></div>
        </div>

        <div class="row">
            {% if perms.chat_app.add_room %}
                <div class="col-md-2">
                <button type="button" id="create" class="btn btn-default"><span class="glyphicon glyphicon-plus text-success"></span>Создать</button>
                </div>
            {% endif %}
            <div class="col-md-7">
                <input type="text" id='txt_message' class="form-control" name="message"/>
            </div>
            <div class="col-md-2">
                <input type="submit" id='submit' class="btn btn-default" value="Отправить"/>
            </div>
        </div>
    </div>
    </div>

</div>
</div>

tornadochat/templates/login.html
{% extends "base.html" %}

{% block content %}
    {% if error %}
        {{ error }}<br><br>
    {% endif %}
    Room users: 
    {% if room_users %} {{ room_users }} {% else %} room is empty {% endif %}
    <form method='POST' action=''> {% csrf_token %}
        <b>Your nickname:</b> <input type='text' name="new_username"> 
        (Please choose unique and not empty nickname)
        <br>
        <input type='submit' value="Join the room">
    </form>
{% endblock %}

tornadochat/templates/main.html
{% extends "base.html" %}

{% block content %}
    {% include 'menu.html' %}

    {% if not is_forum_page %}
        {% include 'chat.html' %}
    {% endif %}

{% endblock %}

tornadochat/templates/menu.html
<div class="row">
    <div class='col-lg-offset-2 col-md-8'>
        <a href = '/' style="color: #E76600">Начало</a>
        <a href = '/news' style="color: #E76600">Новости</a>
        <a href = '/forum' style="color: #E76600">Форум</a>
        <a href = '/shop' style="color: #E76600">Платные услуги</a>
        <a href = '/pedia/main/about' style="color: #E76600">Об игре</a>
        <a href = '/pedia/main/rules' style="color: #E76600">Правила</a>
    </div>
</div>
<hr>

tornadochat/templates/room.html
{#{% extends "base.html" %}#}

{#{% block content %}#}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
var ws;

function get_time() {
    var currentTime = new Date()
    hours = currentTime.getHours()
    minutes = currentTime.getMinutes()
    now_time = '<b>[' + hours + ":" + minutes + '] </b>'
    return now_time
};

$(document).ready(function() {
        ws = new WebSocket("ws://" + location.host + "/websocket/{{room_title}}/{{ user.username }}");
        ws.onopen = function() {
            mess = { 'msgtype':'chat', 'msg': {'room':'{{room_title}}', 'username':'{{user.username}}', 'text':'connect'}};
            ws.send(JSON.stringify(mess));
        }
        ws.onmessage = function(event){
            if (event.data.slice(0, 10) == 'all_users:') {
                $('#online_users').text(event.data.slice(10));
            }
            else if (event.data.slice(0,9) == 'new_user:') {
                user = event.data.slice(9).trim();
                $('#online_users').append('<div id="' + user + '">' + user + '</div>').scrollTop($('#online_users').innerHeight());
            }
            else if(event.data.slice(0, 12) == 'remove_user:'){
                var remove_nick = event.data.slice(12).trim();
                $('#' + remove_nick).remove();
            }
            else {
                $('#chat_text_area').append(get_time() + event.data + '<br />').scrollTop($('#chat_text_area').innerHeight());
            }
        }
        $('#expand').click(function() {
            $('#whole_chat').slideToggle('slow');
        });
    });

$(window).bind('beforeunload', function() {
    mess = { 'msgtype':'chat', 'msg': {'room':'{{room_title}}', 'username':'{{use.username}}', 'text':'disconnect'}};
    ws.send(JSON.stringify(mess));
});

function send_message()
{
    var message = document.getElementById('txt_message')
        if (user.value == '') {
            alert('You cant send empty message')
        } else {
            var json = mess = { 'msgtype':'chat', 'msg': {'room':'{{room_title}}', 'username':'{{user.username}}', 'text':user.value}};
            ws.send(JSON.stringify(json));
            user.value = '';
        }
}

</script>
    <div class="row" id="container">
    <div class="col-md-offset-2 col-md-8">

    <div class="row" style="background-color: rgb(133,133,133)">
        <div class="col-md-1">
            <a id="expand" href="#" style="color: #E76600"><strong>ЧАТ</strong></a>
        </div>
    </div>

    <div class="row" id="whole_chat" style="border-style:solid;border-width:1px;">
    <div class="col-md-12">

    <div class="row" style="height:400px">
        <div class="col-md-8" id="chat_text_area" style="overflow:auto;"></div>
        <div class="col-md-4" style="overflow:auto;">
            <div class="row">
                <div class="col-md-12">
                    {{ form }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12" id="online_users" style="border-style: solid;border-width:1px;height:300px;overflow:auto;">
                </div>
                <a href="#" class="btn btn-default">Смайлы</a>
                <a href="#" class="btn btn-default">Настройки</a>
                <a href="#" class="btn btn-default">Закрыть</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <form class="form-horizontal" role="form">
            <div class="form-group">
                <input type="text" id='txt_message' class="form-control" name="message" />
                <input type="submit" class="btn btn-default pull-right" value="Отправить" onclick="send_message();" />
            </div>
            </form>
        </div>
    </div>
    </div>

    </div>
    </div>

    </div>
    </div>
{#{% endblock %}#}